name: Daily Fact Update

on:
  schedule:
    - cron: '0 0 * * *'  # daily at midnight UTC
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y jq curl gh

      - name: Fetch Daily Fact
        run: |
          FACT=$(curl -s https://uselessfacts.jsph.pl/api/v2/facts/random?language=en | jq -r '.text')
          echo "FACT=$FACT" >> $GITHUB_ENV

      - name: Update README via GitHub API
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          FACT: ${{ env.FACT }}
        run: |
          # Authenticate with GitHub CLI
          gh auth login --with-token <<< "$GH_PAT"

          # Get README SHA
          SHA=$(gh api repos/Ravi123sv/Ravi123sv/contents/README.md | jq -r '.sha')

          # Prepare new content
          NEW_CONTENT=$(curl -s https://raw.githubusercontent.com/Ravi123sv/Ravi123sv/main/README.md \
            | awk -v fact="$FACT" '/### 🌟 Daily Fact/{print;getline;print "> _"fact"_";next}1' \
            | base64 | tr -d '\n')

          # Update README
          gh api \
            -X PUT \
            -H "Accept: application/vnd.github.v3+json" \
            repos/Ravi123sv/Ravi123sv/contents/README.md \
            -f message="Update daily fact" \
            -f content="$NEW_CONTENT" \
            -f sha="$SHA"
