name: Daily Fact Update

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at 00:00 UTC
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y jq curl

      - name: Fetch Daily Fact
        id: fact
        run: |
          FACT=$(curl -s https://uselessfacts.jsph.pl/api/v2/facts/random?language=en | jq -r '.text')
          echo "FACT=$FACT" >> $GITHUB_ENV

      - name: Update README
        run: |
          awk -v fact="$FACT" '/### 🌟 Daily Fact/{print;getline;print "> _"fact"_";next}1' README.md > README.tmp && mv README.tmp README.md

      - name: Commit & Push
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update daily fact" || echo "No changes to commit"
          git push https://$GH_PAT@github.com/Ravi123sv/Ravi123sv.git
